src/Entity/ApiUser.php
<?php

namespace App\Entity;

use App\Repository\ApiUserRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\ManyToOne;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;

#[Entity(repositoryClass: ApiUserRepository::class)]
class ApiUser implements UserInterface
{
    #[ORM\Id]
    #[ORM\Column(type: 'uuid', unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: UuidGenerator::class)]
    private $id;

    #[Column(type: 'string', length: 255)]
    #[NotBlank]
    #[NotNull]
    #[Length(max: 255)]
    private $name;

    #[Column(type: 'string', length: 255)]
    #[NotBlank]
    #[NotNull]
    #[Length(max: 255)]
    private $token;

    #[ManyToOne(targetEntity: Structure::class)]
    #[JoinColumn(nullable: false, onDelete: 'CASCADE')]
    #[NotNull]
    private $structure;

    #[ManyToOne(targetEntity: ApiRole::class)]
    #[JoinColumn(nullable: false)]
    #[NotNull]
    private $apiRole;

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(string $token): self
    {
        $this->token = $token;

        return $this;
    }

    public function getStructure(): ?Structure
    {
        return $this->structure;
    }

    public function setStructure(?Structure $structure): self
    {
        $this->structure = $structure;

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->getApiRole() ? $this->getApiRole()->getComposites() : [];

        return array_unique($roles);
    }

    public function getPassword(): ?string
    {
        return null;
    }

    public function getSalt(): ?string
    {
        return null;
    }

    public function eraseCredentials()
    {
        // Not implemented
    }

    public function getUsername(): string
    {
        return $this->name;
    }

    public function getUserIdentifier(): string
    {
        return $this->getName();
    }

    public function getApiRole(): ?ApiRole
    {
        return $this->apiRole;
    }

    public function setApiRole(?ApiRole $apiRole): self
    {
        $this->apiRole = $apiRole;

        return $this;
    }
}

src/Form/CsvType.php
<?php

namespace App\Form;

use App\Form\Type\LsFileType;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\NotNull;

class CsvType extends AbstractType
{
    public function __construct(private readonly ParameterBagInterface $bag)
    {
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $csvMaxSize = $this->bag->get('csv_max_size');

        $builder
            ->add('csv', LsFileType::class, [
                'label' => 'Fichier csv',
                'required' => true,
                'multiple' => false,
                'attr' => [
                    'placeholder' => 'Sélectionner un csv',
                    'accept' => '.csv',
                ],
                'constraints' => [
                    new NotNull(null, 'Le fichier est obligatoire'),
                    new File([
                        'mimeTypes' => $this->bag->get('csv_mime_types_authorized'),
                        'mimeTypesMessage' => "Le fichier doit être au format '.csv'",
                        'maxSize' => $csvMaxSize,
                        'maxSizeMessage' => sprintf('Le fichier doit faire moins de %s', $csvMaxSize),
                    ]),
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([]);
    }
}

src/Controller/Csv/CsvThemeController.php
<?php

namespace App\Controller\Csv;

use App\Form\CsvType;
use App\Service\Csv\CsvThemeManager;
use App\Sidebar\Annotation\Sidebar;
use APY\BreadcrumbTrailBundle\Annotation\Breadcrumb;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Sidebar(active: ['theme-nav'])]
#[Breadcrumb(title: 'Utilisateurs', routeName: 'user_index')]
class CsvThemeController extends AbstractController
{
    #[Route(path: '/csv/importTheme', name: 'csv_add_themes')]
    #[IsGranted('ROLE_MANAGE_THEMES')]
    #[Breadcrumb(title: 'Importer des utilisateurs via csv')]
    public function importTheme(Request $request, CsvThemeManager $csvThemeManager, Session $session): Response
    {
        $form = $this->createForm(CsvType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $errors = $csvThemeManager->importThemes($form->get('csv')->getData(), $this->getUser()->getStructure());
            if (empty($errors)) {
                $this->addFlash('success', 'Fichier csv importé avec succès');

                return $this->redirectToRoute('theme_index');
            }
            $session->set('errors_theme_csv', $errors);

            return $this->redirectToRoute('theme_csv_error');
        }

        return $this->render('csv/importThemeCsv.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route(path: '/csv/themeErrors', name: 'theme_csv_error')]
    #[IsGranted('ROLE_MANAGE_THEMES')]
    #[Breadcrumb(title: "Erreurs lors de l'import")]
    public function csvUsersError(Session $session): Response
    {
        $errors = $session->get('errors_theme_csv');
        if (empty($errors)) {
            return $this->redirectToRoute('theme_index');
        }
        $session->remove('theme_csv_error');

        return $this->render('csv/importThemeCsvErrors.html.twig', [
            'errors' => $errors,
        ]);
    }
}

src/Controller/Csv/CsvUserController.php
<?php

namespace App\Controller\Csv;

use App\Form\CsvType;
use App\Service\Csv\CsvUserManager;
use App\Sidebar\Annotation\Sidebar;
use APY\BreadcrumbTrailBundle\Annotation\Breadcrumb;
use League\Csv\Exception;
use League\Csv\UnavailableStream;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Sidebar(active: ['user-nav'])]
#[Breadcrumb(title: 'Utilisateurs', routeName: 'user_index')]
class CsvUserController extends AbstractController
{
    /**
     * @throws UnavailableStream
     * @throws Exception
     */
    #[Route(path: '/csv/importUsers', name: 'csv_add_users')]
    #[IsGranted('ROLE_MANAGE_USERS')]
    #[Breadcrumb(title: 'Importer des utilisateurs via csv')]
    public function importUsers(Request $request, CsvUserManager $csvUserManager, Session $session): Response
    {
        $form = $this->createForm(CsvType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $errors = $csvUserManager->importUsers($form->get('csv')->getData(), $this->getUser()->getStructure());
            if (empty($errors)) {
                $this->addFlash('success', 'Fichier csv importé avec succès');

                return $this->redirectToRoute('user_index');
            }
            $session->set('errors_csv', $errors);

            return $this->redirectToRoute('user_csv_error');
        }

        return $this->render('csv/importCsv.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route(path: '/csv/userErrors', name: 'user_csv_error')]
    #[IsGranted('ROLE_MANAGE_USERS')]
    #[Breadcrumb(title: "Erreurs lors de l'import")]
    public function csvUsersError(Session $session): Response
    {
        $errors = $session->get('errors_csv');
        if (empty($errors)) {
            return $this->redirectToRoute('user_index');
        }
        $session->remove('errors_csv');

        return $this->render('csv/importCsvErrors.html.twig', [
            'errors' => $errors,
        ]);
    }
}

src/Controller/Csv/ExportUsersController.php
<?php

namespace App\Controller\Csv;

use App\Entity\Group;
use App\Entity\Structure;
use App\Entity\User;
use App\Service\Csv\ExportUsersCsv;
use League\Csv\CannotInsertRecord;
use League\Csv\Exception;
use League\Csv\UnavailableStream;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class ExportUsersController extends AbstractController
{
    public function __construct(
        private readonly ExportUsersCsv $exportUsersCsv,
    ) {
    }


    /**
     * @throws UnavailableStream
     * @throws CannotInsertRecord
     * @throws Exception
     */
    #[Route('/export/csv/structure/users', name: 'export_csv_users', methods: ['GET'])]
    #[IsGranted('ROLE_MANAGE_USERS')]
    public function exportCsvUsers(): Response
    {
        $structure = $this->getUser()->getStructure();
        $response = new BinaryFileResponse($this->exportUsersCsv->exportStructureUsers($structure));
        $response->setContentDisposition(
            ResponseHeaderBag::DISPOSITION_ATTACHMENT,
            $structure->getName() . '.csv'
        );

        $response->deleteFileAfterSend();

        return $response;
    }

    #[Route('/export/csv/group/{id}/users', name: 'export_csv_users_group', methods: ['GET'])]
    #[isGranted('MANAGE_GROUPS', subject: 'group')]
    public function exportCsvUsersFromGroup(Group $group): Response
    {
        $response = new BinaryFileResponse($this->exportUsersCsv->exportGroupUsers($group));
        $response->setContentDisposition(
            ResponseHeaderBag::DISPOSITION_ATTACHMENT,
            $group->getName() . '.zip'
        );

        $response->deleteFileAfterSend();

        return $response;
    }
}

templates/csv/importCsv.html.twig
{% extends 'form.html.twig' %}
{% import 'macro/_forms.html.twig' as macro %}

{% block pageTitle 'Importer des utilisateurs via csv' %}

{% block pageActions %}
    {{ macro.backButton('user_index') }}
{% endblock %}

{% block pageDetails %}
    <div class="alert alert-info">
        Information : Votre csv doit être construit de la manière suivante : <br>
        Ne pas mettre les noms des colonnes mais directement les utilisateurs <br>
        Le séparateur est le caractère "," <br>

        champ 1 : Civilité
        <ul>
            <li>Non précisé : 0</li>
            <li>Madame : 1</li>
            <li>Monsieur : 2</li>
        </ul>
        champ 2 : Nom d'utilisateur <br>
        champ 3 : Prénom <br>
        champ 4 : Nom <br>
        champ 5 : Email <br>
        champ 6 : Profil
        <ul>
            <li>Gestionnaire de séance : 1</li>
            <li>Administrateur : 2</li>
            <li>Élu : 3</li>
            <li>Personnel administratif : 4</li>
            <li>Invité : 5</li>
            <li>Suppléant : 6</li>
        </ul>
        champ 7 : Numéro de téléphone. Le format du numéro doit être le suivant : 06XXXXXXXX ou 07XXXXXXXX <br>
        champ 8 : Titre (uniquement si l'utilisateur est un élu) <br>
        champ 9 : Nom d'utilisateur du suppléant (uniquement si l'utilisateur est un élu) <br>
        <br>
        Exemple : <br>
        2,d.martin,Damien,Martin,d.martin@exemple.org,2,0612345678<br>
        1,e.durant,Emilie,Durant,e.durant@exemple.org,3,0709455321, conseiller, n.pascal <br>
        <b>Attention :</b> Si un acteur existe déja alors il ne sera pas modifié.
    </div>
{% endblock %}

{% block pageForm %}
    {{ form_start(form) }}
    {{ form_row(form.csv) }}
    {{ form_errors(form.csv) }}

    <div class="alert alert-warning">
        Attention : L'import des utilisateurs peut durer plusieurs dizaines de secondes
    </div>

    <div class="float-end">
        {% block pageSaveReturn %}{{ macro.save('user_index', {}, 'Importer le csv', 'fa fa-plus-circle') }}{% endblock %}
    </div>

    {{ form_end(form) }}
{% endblock %}

{% block javascripts %}
    <script>
        let freezeClick = false;

        let formCsv = document.getElementsByName("csv")[0];
        formCsv.onsubmit = () => {
            freezeClick = true;
        }

        document.addEventListener("click", e => {
            if (freezeClick) {
                console.log('clicks are disabled');
                e.stopPropagation();
                e.preventDefault();
            }
        }, true);
    </script>
{% endblock %}

templates/csv/importCsvErrors.html.twig
{% extends 'form.html.twig' %}
{% import 'macro/_forms.html.twig' as macro %}

{% block pageTitle 'Erreurs lors de l\'import' %}

{% block pageActions %}
    {{ macro.backButton('user_index') }}
{% endblock %}

{% block pageDetails %}
    <div class="alert alert-primary">
        Certains utilisateurs n'ont pas pu être importés
    </div>

    {% for error in errors %}
        <div class="alert alert-danger">

            {% for violation in error %}
                {% if violation.root.username is defined %}
                    Entrée : {{ violation.root.username }}, {{ violation.root.firstName }}, {{ violation.root.lastName }}
                    , {{ violation.root.lastName }} <br>
                    Message : {{ violation.message }} <br>
                    Champ en erreur : {{ violation.propertyPath }} <br>
                    Valeur du champ : {{ violation.invalidValue }} <br>
                {% else%}
                    Entrée : {{ violation.parameters | join(',') }} <br>
                    Message: {{ violation.message }} <br>
                {% endif %}

                {% if not loop.last %}
                    <hr>
                {% endif %}
            {% endfor %}
        </div>
    {% endfor %}
{% endblock %}

{% block pageForm %}
{% endblock %}

templates/csv/importThemeCsv.html.twig
{% extends 'form.html.twig' %}
{% import 'macro/_forms.html.twig' as macro %}

{% block pageTitle 'Importer des thèmes via csv' %}

{% block pageActions %}
    {{ macro.backButton('theme_index') }}
{% endblock %}

{% block pageDetails %}
    <div class="alert alert-info">
        Information : Votre csv doit être construit de la manière suivante : <br>

        champ 1 : Intitulé du thème <br>
        <br>
        Pour importer des sous-thèmes, ceux-ci doivent être séparés par une virgule du thème de niveau supérieur, et la ligne doit être entre guillemets.
        Exemple : <br>
        Administration générale<br>
        "Finances,Budget"<br>
        "Finances,Comptabilité"<br>
    </div>
{% endblock %}

{% block pageForm %}
    {{ form_start(form) }}
    {{ form_row(form.csv) }}
    {{ form_errors(form.csv) }}
    <div class="alert alert-warning">Attention : L'import des themes peut durer plusieurs dizaines de secondes</div>

    <div class="float-end">
        {% block pageSaveReturn %}{{ macro.save('theme_index') }}{% endblock %}
    </div>

    {{ form_end(form) }}
{% endblock %}

{% block javascripts %}
    <script>
        let freezeClick = false;

        let formCsv = document.getElementsByName("csv")[0];
        formCsv.onsubmit = () => {
            freezeClick = true;
        }

        document.addEventListener("click", e => {
            if (freezeClick) {
                console.log('clicks are disabled');
                e.stopPropagation();
                e.preventDefault();
            }
        }, true);
    </script>
{% endblock %}

templates/csv/importThemeCsvErrors.html.twig
{% extends 'form.html.twig' %}
{% import 'macro/_forms.html.twig' as macro %}

{% block pageTitle 'Erreurs lors de l\'import' %}

{% block pageActions %}
    {{ macro.backButton('theme_index') }}
{% endblock %}

{% block pageDetails %}
    <div class="alert alert-primary">
        Certains thèmes n'ont pas pu être importés
    </div>

    {% for error in errors %}
        <div class="alert alert-danger">
            {% for violation in error %}
                Entrée : {{ violation.parameters | join(',') }} <br>
                Message: {{ violation.message }} <br>

                {% if not loop.last %}
                    <hr>
                {% endif %}
            {% endfor %}
        </div>
    {% endfor %}
{% endblock %}

{% block pageForm %}
{% endblock %}